#!/usr/bin/env php
<?php
/**
 * Created by Maatify.dev
 * User: Maatify.dev
 * Date: 2025-11-05
 * Time: 08:40
 * Project: maatify/psr-logger
 * IDE: PhpStorm
 * https://www.Maatify.dev
 *
 * Description:
 * CLI tool to automatically clean old logs generated by Maatify PSR Logger.
 * Can be executed directly or scheduled via CRON jobs.
 *
 * Example usage:
 * ```bash
 * chmod +x scripts/clean-logs.php
 * ./scripts/clean-logs.php
 * ```
 *
 * Example cron configuration:
 * ```bash
 * 0 0 * * * /usr/bin/php /var/www/project/vendor/maatify/psr-logger/scripts/clean-logs.php >> /var/www/project/storage/logs/cron.log 2>&1
 * ```
 */

declare(strict_types=1);

/**
 * Smart base directory detection:
 * - If installed inside `vendor/maatify/psr-logger`, move 3 levels up to reach project root.
 * - If running standalone (for development or testing), move one level up from /scripts.
 */
$baseDir = getDirname();

use Dotenv\Dotenv;
use Maatify\PsrLogger\Rotation\LogCleaner;

// Load environment variables (if .env exists)
if (file_exists($baseDir . '/.env')) {
    Dotenv::createImmutable($baseDir)->load();
}

// 🧹 Execute log cleanup
LogCleaner::cleanOldLogs();

echo "✅ Old logs cleaned successfully.\n";
